language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-27
    - add-on
    - extra
licenses:
    - 'android-sdk-license-.+'

jdk:
- oraclejdk8
script:
  - wget https://raw.githubusercontent.com/TwrpBuilder/TwrpBuilder/master/build.sh
  - chmod +x build.sh && ./build.sh
  - "./gradlew build"
  - "mv ./app/build/outputs/apk/release/app-release.apk ./TwrpBuilder-$(git describe --tags).apk"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN_TB"
  file: "./TwrpBuilder-$(git describe --tags).apk"
  on:
    tags: true
before_install:
      - yes | sdkmanager "platforms;android-27"

